# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'onechurch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for onechurch
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'onechurch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'onechurchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
